# Generated by Django 5.0.1 on 2024-01-25 01:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0001_initial'),
        ('post', '0002_alter_post_author_alter_post_title'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Author',
        ),
    ]
